apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akka-simple-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: akka-simple-cluster
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      serviceAccountName: akka-simple-cluster
      containers:
        - image: softwaremill/akka-simple-cluster-k8s:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: akka-simple-cluster
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - name: remoting
              containerPort: 2551
            - name: api
              containerPort: 8080
            - name: management
              containerPort: 8558
          #health
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            initialDelaySeconds: 30
          #health
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "30"]